### ISSUE TITLE
User model is broken

### ISSUE THREAD

**Issue by enricostano** [coopdevs/timeoverflow#365]
```
Loading production environment (Rails 4.2.10)
irb(main):001:0> User.last
  User Load (1.6ms)  SELECT  "users".* FROM "users"  ORDER BY users.id DESC LIMIT 1
ArgumentError: wrong number of arguments (given 0, expected 1)
	from /var/www/timeoverflow/shared/bundle/ruby/2.3.0/gems/devise-4.4.1/lib/devise/models/database_authenticatable.rb:166:in `password_digest'
	from /var/www/timeoverflow/shared/bundle/ruby/2.3.0/gems/activemodel-4.2.10/lib/active_model/serialization.rb:108:in `block in serializable_hash'
	from /var/www/timeoverflow/shared/bundle/ruby/2.3.0/gems/activemodel-4.2.10/lib/active_model/serialization.rb:108:in `each'
	from /var/www/timeoverflow/shared/bundle/ruby/2.3.0/gems/activemodel-4.2.10/lib/active_model/serialization.rb:108:in `serializable_hash'
	from /var/www/timeoverflow/shared/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/serialization.rb:17:in `serializable_hash'
	from /var/www/timeoverflow/shared/bundle/ruby/2.3.0/gems/devise-4.4.1/lib/devise/models/authenticatable.rb:116:in `serializable_hash'
	from /var/www/timeoverflow/shared/bundle/ruby/2.3.0/gems/devise-4.4.1/lib/devise/models/authenticatable.rb:122:in `inspect'
	from /var/www/timeoverflow/shared/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/commands/console.rb:110:in `start'
	from /var/www/timeoverflow/shared/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/commands/console.rb:9:in `start'
	from /var/www/timeoverflow/shared/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /var/www/timeoverflow/shared/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /var/www/timeoverflow/shared/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by sauloperez** [comment]
@markets @rewritten could any of you take a quick look? @enricostano and I are very busy and this is rather urgent. Thanks in advance!

**Comment by markets** [comment]
hi guys 👋 I made a quick look and I think the problem is: the `users` table has a password_digest column: 

https://github.com/coopdevs/timeoverflow/blob/dad31b672ad28f165ef7666dcd4ae58182cf850a/db/schema.rb#L180

This is not coming from `devise` migration (should be something from the pre-`devise` era), but `devise` has a method named `password_digest` (https://github.com/plataformatec/devise/blob/d98f38cf5fbbd0e7395948eacaa8d5a4a7f7428c/lib/devise/models/database_authenticatable.rb#L166), which accepts a param. So it seems that AR (column => attribute inference) is conflicting with that method provided by `devise`. 

**Proposed solution:** create a migration removing this column from the `users` table.

**Comment by markets** [comment]
Confirmed:

https://github.com/plataformatec/devise/issues/4192#issuecomment-232651031

> I think in your case the best option is to remove the password_digest column from the users table as Devise uses the encrypted_password instead.

**Comment by sauloperez** [comment]
Awesome @markets! It totally makes sense.

**Comment by enricostano** [comment]
Nice work @markets :clap: 

BTW.. for the sake of history, I found the commit that introduces it: https://github.com/coopdevs/timeoverflow/commit/dfe266bf9bb34b433d29c634c13c9ff176991f8d
