### ISSUE TITLE
member_uid order

### ISSUE THREAD

**Issue by sseerrggii** [coopdevs/timeoverflow#398]
Related with https://github.com/coopdevs/timeoverflow/pull/354

Now is ordering by ID alphabetically but we need numerically order

I only see it in produccion, with more than 99 members :sweat_smile: 
![fireshot capture 2 - banc del temps de gracia - https___www timeoverflow org_members](https://user-images.githubusercontent.com/2297137/43903106-f840f1e0-9beb-11e8-8a7f-5c4966bd0922.png)

**Comment by enricostano** [comment]
@markets could this be related to the casting to String in your PR?

**Comment by markets** [comment]
Maybe! I'll take a look this night, but is this the default order when you visit the page, or after clicking the sort link? If we're talking about the later, I'd say yes, since the sort is also implemented via Ransack, probably they use the defined casting for all features (filter and order). If so, I think the only solution will be to remove the (Ransack) sort on that column (I think it wouldn't be a problem, since it was kind of **extra** 😛).

**Comment by sseerrggii** [comment]
Hi @markets  
Both orders are aphabetic now
* the default order when you visit the page
* after clicking the sort link

**Comment by markets** [comment]
ok thanks for the info @sseerrggii! I just reproduce it in staging. The weird thing is that I can't reproduce it in my local environment :(

![captura de pantalla 2018-08-09 a la s 21 19 45](https://user-images.githubusercontent.com/576701/43920749-1a087860-9c1a-11e8-8b10-da6427b1c234.png)

@sauloperez @enricostano what version of PostgreSQL are we running in our current infra? I realized I'm running and old version (9.3), and I suppose this might be related (since I used an internal PostgreSQL helper):

https://github.com/coopdevs/timeoverflow/blob/c4fb4aa2953935083effeddfe494c50a09ff7ffb/app/models/member.rb#L3-L5

About possible solutions:
- Implement search without Ransack
- Avoid the casting via adding a second input to search by member_ui (not nice UX)

**Comment by enricostano** [comment]
@markets `9.4.5` in `production` and `9.5.12` in `staging`... :sweat_smile:

**Comment by markets** [comment]
Hi @enricostano @sauloperez :wave: 

I think I've found a different fix: #399 

Let me know what do you think

**Comment by markets** [comment]
New approach pushed in a different branch, so now we have a couple of solutions, both solve the issue, so we just need to decide what solution we prefer:

- #399: move `member_uid` to use `_eq` by mapping params manually
- #400: rename `ransacker` to only use the cast when filtering

**Comment by enricostano** [comment]
Many thanks @markets and @mllocs for dealing with this, I also prefer the second option :muscle:
